version: '3.4'

services:
  todoapi:
    image: szyale/todoapi:latest
    ports:
        - target: 443
          published: 4444
          protocol: tcp
    build:
      context: .
      dockerfile: TodoApi/Dockerfile
    depends_on:
        - "postgresql_database"



  postgresql_database:
    image: postgres:latest
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=TestDB
    ports:
        - "5432:5432"
    restart: unless-stopped
    volumes: 
        - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
